# Generated by Django 4.1.7 on 2023-03-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_report_coordx_report_coordy_report_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agency',
            field=models.CharField(choices=[('P', 'Police'), ('T', 'Transportation'), ('F', 'Fire'), ('H', 'Health'), ('S', 'Sanitation'), ('U', 'Utilities'), ('O', 'Other')], default='P', max_length=1),
        ),
    ]
