# Generated by Django 4.1.7 on 2023-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Solved')], default='P', max_length=1),
        ),
    ]
