# Generated by Django 4.1.7 on 2023-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
