# Generated by Django 4.1.7 on 2023-03-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
        ('main_app', '0005_report_status'),
    ]

    operations = [
    ]
